import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import { collection, FieldValue, getDocs, Timestamp } from 'firebase/firestore';
import { db } from '../lib/firebase';
import TambahItem from '../components/store/TambahItem';
import Toast from '../components/utilities/Toast';
import BeliItem from '../components/store/BeliItem';
import ItemCard from '../components/store/ItemCard';

export interface IItemData {
  item_id: string;
  item_name: string;
  item_description: string;
  item_price: number;
  item_img: string;
  item_img_ref: string;
  item_created_at: Timestamp;
}

const Home: NextPage = () => {
  const [items, setItems] = React.useState<IItemData[]>([]);
  const [isLoading, setIsLoading] = React.useState<boolean>(true);
  const [fetchToggle, setFetchToggle] = React.useState<boolean>(true);

  const getAllItem = async () => {
    setIsLoading(true);
    const querySnapshot = await getDocs(collection(db, 'items'));
    querySnapshot.forEach((doc) => {
      setItems((prev) => {
        const arr = [...prev];
        const newItem = { ...doc.data(), item_id: doc.id };
        if (!arr.some((data) => data.item_id === doc.id)) {
          arr.push(newItem as IItemData);
        }
        return arr;
      });
    });
    setIsLoading(false);
  };

  const toggleRefetch = () => {
    setFetchToggle((prev) => !prev);
  };

  React.useEffect(() => {
    getAllItem();
  }, [fetchToggle]);

  return (
    <>
      <Head>
        <title>Kantin Kejujuran</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Toast isLoading={isLoading} />
      <div className='bg-purple-50 flex flex-col items-center justify-center min-h-screen py-20'>
        <div className='flex gap-x-10 items-center justify-between mx-20 w-full'>
          <span className='w-1/3'></span>
          <div className='text-center w-1/3'>
            <h1>Kantin Kejujuran</h1>
            <h4>SD SEA Sentosa</h4>
          </div>
          <div className='text-center w-1/3'>
            <TambahItem toggleRefetch={toggleRefetch} setItems={setItems} />
          </div>
        </div>
        <div className='min-h-[20rem] mx-20 my-10'>
          <div className='flex flex-wrap gap-3 justify-center'>
            {isLoading ? (
              [0, 1, 2].map((i) => {
                return (
                  <span
                    key={i}
                    className='animate-pulse bg-gradient-to-b from-slate-200 h-60 rounded-md to-purple-50 w-80'
                  ></span>
                );
              })
            ) : items.length === 0 ? (
              <p className='mt-5 text-slate-700'>
                Tidak ada item, tekan{' '}
                <span className='font-semibold'>Tambah Item</span> untuk
                menambahkan
              </p>
            ) : (
              items.map((item, i) => {
                return (
                  <ItemCard
                    key={i}
                    item={item}
                    toggleRefetch={toggleRefetch}
                    setItems={setItems}
                  />
                );
              })
            )}
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
